### ISSUE TITLE
Images for PLV8 v3.1

### ISSUE THREAD

**Issue by andreas** [sibedge-llc/plv8-build#2]
Hi @alexeyfadeev -- appreciate this repo, it makes it much easier to get started with `plv8`! 🙏 

I was wondering whether images for PLV8 v3.1 are on the horizon? Thanks in advance.

**Comment by alexeyfadeev** [comment]
Already published for alpine and Postgres 14.
All other (apine-pg13, debian-pg13, debian-pg14) will be published soon.
Pay attention, default plv8 build can not serialize BigInt right (BigInt values are converted into string). So, we publish tho images: default and with BigInt serialization support.

docker pull sibedge/postgres-plv8
docker pull sibedge/postgres-plv8-bigint

**Comment by andreas** [comment]
Oh, amazing! I didn't think to check Dockerhub -- thanks. For future reference, here are direct links:

- https://hub.docker.com/r/sibedge/postgres-plv8
- https://hub.docker.com/r/sibedge/postgres-plv8-bigint
