### ISSUE TITLE
Build ARM64 image versions

### ISSUE THREAD

**Issue by threesquared** [sibedge-llc/plv8-build#3]
Do you have any plans to build an ARM64 version?

**Comment by alexeyfadeev** [comment]
Maybe, but not in the near future.

**Comment by alexeyfadeev** [comment]
@threesquared , we have built and published alpine based images for arm64
[sibedge/postgres-plv8](https://hub.docker.com/r/sibedge/postgres-plv8)
[sibedge/postgres-plv8-bigint](https://hub.docker.com/r/sibedge/postgres-plv8-bigint)
Welcome to use

**Comment by threesquared** [comment]
Amazing, thanks so much

**Comment by alexeyfadeev** [comment]
@threesquared , hi!

We are writing an article about our images with PLV8.
Could you please share what you are using PLV8 for?
How did our build for arm64 help you?

**Comment by threesquared** [comment]
So we use the PLV8 extension on RDS in AWS but then providing a Postgres image for local dev that also had that extension proved problematic once developers started using M1 laptops. We managed to get it working eventually (even though RDS uses PLV8 2.3.15?? But the latest versions seem to be fine for our use case) but your images are much more convenient to use as a base. So thank you!
